name: Delete

on: 
  repository_dispatch:
  workflow_dispatch:

# 定时触发编译
  schedule:
    - cron: 0 */1 * * *

# 点赞☆Star触发编译
#  watch:
#    types: [started]

jobs:
  Update:
    runs-on: ubuntu-20.04
    steps:
    - name: Clone Repository
      uses: actions/checkout@v4

    - name: Set git
      run : |
        git config --global user.email "109743406+zijieKwok@users.noreply.github.com"
        git config --global user.name "zijieKwok"
        sudo timedatectl set-timezone "Asia/Shanghai"

    - name: Delete workflow runs
      uses: Mattraks/delete-workflow-runs@main
      continue-on-error: true
      with:
        retain_days: 1
        keep_minimum_runs: 0  
        
    - name: Update
      run: |

        rm -rf ./luci-app-pushbot
        rm -rf ./op-alist
        rm -rf ./op-mosdns
        rm -rf ./op-smartdns
        # rm -rf ./luci-app-unblockneteasemusic
        # rm -rf ./linkease/*   
        rm -rf ./op-ddnsgo
        rm -rf ./luci-app-oled
        rm -rf ./patch
        rm -rf ./op-daed
        rm -rf ./op-lucky
        
         
        
        
        
    - name: Apply
      run: |
        git add .
        git commit -m "Auto Sync: $(date +%Y-%m-%d" "%H:%M)"
        git push -f 
              
