name: Update.linkease
on: 
  repository_dispatch:
  workflow_dispatch:

# 定时触发编译
#  schedule:
#    - cron: 0 */1 * * *

# 点赞☆Star触发编译
#  watch:
#    types: [started]

jobs:
  Update:
    runs-on: ubuntu-20.04
    steps:
    - name: Clone Repository
      uses: actions/checkout@v4

    - name: Set git
      run : |
        git config --global user.email "194788255+Jaykwok2999@users.noreply.github.com"
        git config --global user.name "Jaykwok2999"
        sudo timedatectl set-timezone "Asia/Shanghai"

    - name: Delete workflow runs
      uses: Mattraks/delete-workflow-runs@main
      continue-on-error: true
      with:
        retain_days: 1
        keep_minimum_runs: 0  
        
    - name: Update
      run: |

        rm -rf ./linkease/*
        
        
         
        git clone https://github.com/linkease/nas-packages-luci ./linkease/nas-packages-luci
        mv ./linkease/nas-packages-luci/luci ./linkease/
        rm -rf ./linkease/nas-packages-luci
        rm -rf ./linkease/luci/luci-app-quickstart/htdocs/luci-static/quickstart/index.js
        cp -af ./patch/diy/index.js linkease/luci/luci-app-quickstart/htdocs/luci-static/quickstart/
        sed -i 's/services/nas/g' linkease/luci/luci-app-linkease/luasrc/controller/linkease.lua
        sed -i 's/services/nas/g' linkease/luci/luci-app-linkease/luasrc/view/linkease_status.htm
        git clone https://github.com/linkease/nas-packages ./linkease/nas-packages
        mv ./linkease/nas-packages/multimedia/ffmpeg-remux ./linkease/nas-packages/
        mv ./linkease/nas-packages/network/services/* ./linkease/nas-packages/
        rm -rf ./linkease/nas-packages/multimedia
        rm -rf ./linkease/nas-packages/network
        rm -rf ./linkease/nas-packages/.git
        rm -rf ./linkease/nas-packages/README.md
        
    - name: Apply
      run: |
        Emoji=("🎉" "🤞" "✨" "🎁" "🎈" "🎄" "🎨" "💋" "🍓" "🍕" "🍉" "💐" "🌴" "🚀" "🛸" "🗽" "⛅" "🌈" "🔥" "⛄" "🐶" "🏅" "🦄" "🐤")
        git add .
        git commit -m "${Emoji[$[$RANDOM % ${#Emoji[@]}]]} Sync $(date +%Y-%m-%d" "%H:%M:%S)"
        for pkg in $(git diff-tree --no-commit-id --name-only HEAD); do
          if [ "$(grep "PKG_RELEASE" $pkg/Makefile)" ]; then
            sed -i "s/PKG_RELEASE:=.*/PKG_RELEASE:=$(git rev-list --count main $pkg)/" $pkg/Makefile || true
          fi
        done
        git reset --soft HEAD^
        git add .
        git commit -m "${Emoji[$[$RANDOM % ${#Emoji[@]}]]} Sync $(date +%Y-%m-%d" "%H:%M:%S)"
        git push -f
